// for (let index = 0; index < array.length; index++) {
//     const element = array[index];
    
// }

//this is syntax generated by code editor


//our syntax to write for loop 

for(let i=0;i<=100;i++){
    let value = [i];
   // console.log(value);
    //console.log(typeof(value))
}


for (let i = 0; i < 5; i++) {
   // console.log(`outer value is ${i}`)
    for (let j = 0; j < 10; j++) {
       //console.log(`inner value is ${j} and outer value is ${i} `)
        
    }
    
}

// print the table of 1 to 50;
for (let i = 0; i <= 50; i++) {
    // const element = array i];
    //console.log( "table of :",i )

    for (let j = 0; j <= 10; j++) {
        // const element = array[j];
        //console.log(`${i}*${j}=${i*j}`)
        
    }
}
let myArray = ["batman","sharukhan","spiderman"]
//console.log(myArray.length)

for (let index = 0; index < array.length; index++) {
    const element = array[index];
    //console.log(element)
    
}




//break and continue concept


for(i=0;i<=20;i++){
    if(i===5){
        console.log("detected value 5")
        break;
    }
    console.log(`value of i is ${i}`)
}





